var status = {
  STATUS_OK: 0,
  WRONG_JSON: 1,
  WRONG_TOKEN: 2,
  EMAIL_IS_ALREADY_TAKEN: 3,
  PASSWORD_INCORRECT_FORMAT: 4,
  USER_DOES_NOT_EXIST: 5,
  WRONG_PASSWORD: 6,
  OTHER_USER_OWNS_THIS_ARDUINO_ID: 7,
  USER_DOES_NOT_OWN_ARDUINO_ID: 8,
  INVALID_PERIOD: 9,
  DEVICE_NAME_INCORRECT_FORMAT: 10,
  USER_NAME_INCORRECT_FORMAT: 11,
  EMAIL_INCORRECT_FORMAT: 12,
  SERVER_ERROR: 13,
  TOKEN_EXPIRED: 14,
  DEVICE_ALREADY_EXISTS: 15,
  DEVICE_ID_INCORRECT_FORMAT: 16
}

module.exports = status;
